### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by fzp0** [voidzer0-development/reflect.codes-source#1]
can you atl unblock me on discord so i can explain the situation? instead of you acting like a crybaby and ignoring any attempt from me to communicate
Please just one last time and you do not have to talk to me again

**Comment by notgoodusename** [comment]
Just post it here, you can delete your comment later

**Comment by SightDev** [comment]
@notgoodusename this is the last place i expected to see you

**Comment by notgoodusename** [comment]
> this is the last place i expected to see you

i was a dev in this project

**Comment by SightDev** [comment]
> > this is the last place i expected to see you
> 
> i was a dev in this project

ah

**Comment by codecheck01** [comment]
@notgoodusename Can you add me on Discord real quick, Thiblizz#5431
