### ISSUE TITLE
shit just doesnt wanna compile

### ISSUE THREAD

**Issue by smazony** [voidzer0-development/reflect.codes-source#12]
im by no means good at doing anything in visual studio. i did compile few things in the past with pretty much no issues but THIS FUCKING SHIT IS MAKING ME GO INSANE. ive been trying to fix this for about a day now but everytime i try to fix it i keep getting even more errors. if someone succesfuly compiled this thing, pls tell me how u did it cuz im going fucking mad

**Comment by voidzero666** [comment]
Please provide some info thank you

**Comment by Synth1a** [comment]
On my fork there should be everything you need to know

**Comment by smazony** [comment]
oh thx bro hope u didnt rat it or something lol

**Comment by smazony** [comment]
\reflect.codes-source-main\solution\Recorder.cpp(74,1): fatal  error C1001: 
the recorder.cpp causes the issue when compiling i found a fix for every other problem i had in the beginning but i cant figure this one out

rn im just trying to just delete the recorder function cuz i dont rly need it

**Comment by smazony** [comment]
oh nvm im just retarded i got it
