### ISSUE TITLE
ez

### ISSUE THREAD

**Issue by trash1sland** [voidzer0-development/reflect.codes-source#2]
under dogs is mad af xddd leeel

**Comment by 780u363521** [comment]
download visual studio and compile components, press debug

**Comment by kakadou** [comment]
IQ

**Comment by SightDev** [comment]
He needs to go buy a brain

**Comment by RoksanaKregiel** [comment]
> He needs to go buy a brain

indeed true

**Comment by trash1sland** [comment]
> > He needs to go buy a brain
> 
> indeed true

calm down LOL ima just dont update dat stupid vscode go kys
