### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by Synth1a** [voidzer0-development/reflect.codes-source#9]
Hello, I've noticed Im not the only one having compiler errors while trying to build the Source. Does anyone have a fix?

**Comment by Synth1a** [comment]
Its a problem on Recorder.cpp btw

**Comment by szlug3ns** [comment]
You cant really do anything because it seems like the compilers fault. You can also try to remove the feature but that might be hard.

**Comment by Synth1a** [comment]
Yeah im pretty new to cpp too so i wouldnt really know how to do it
